apiVersion: batch/v1
kind: Job
metadata:
  name: matrix-cuda
  labels:
    app: matrix-cuda
spec:
  completions: 4
  parallelism: 4
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: matrix-cuda
    spec:
      restartPolicy: Never
      containers:
      - name: matrix-cuda
        image: justin0u0/matrix-cuda:latest
        imagePullPolicy: Always
        command:
        - matrix-cuda # do matrix multiplication n*m*k t times
        - "8000" # n
        - "8000" # m
        - "8000" # k
        - "20"   # t
        resources:
          limits:
            nvidia.com/gpu: 1
